# Generated by Django 4.2 on 2025-09-24 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número de Despacho')),
                ('beneficiary', models.CharField(blank=True, max_length=200, verbose_name='Nombre del Beneficiario')),
                ('order_number', models.CharField(blank=True, max_length=50, verbose_name='N° de Orden Asociada')),
                ('dispatch_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Despacho')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('DISPATCHED', 'Despachado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total')),
                ('driver_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Conductor')),
                ('driver_id', models.CharField(blank=True, max_length=20, verbose_name='C.I. del Conductor')),
                ('vehicle_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo de Vehículo')),
                ('vehicle_color', models.CharField(blank=True, max_length=50, verbose_name='Color del Vehículo')),
                ('license_plate', models.CharField(blank=True, max_length=20, verbose_name='Placa')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Nota de Despacho',
                'verbose_name_plural': 'Notas de Despacho',
                'ordering': ['-dispatch_date'],
            },
        ),
        migrations.CreateModel(
            name='DispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Subtotal')),
                ('dispatch_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dispatch_notes.dispatchnote', verbose_name='Nota de Despacho')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Artículo de Despacho',
                'verbose_name_plural': 'Artículos de Despacho',
            },
        ),
    ]
