# Generated by Django 4.2 on 2025-08-21 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_rename_cost_product_unit_price_product_category_and_more'),
        ('dispatch_notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchnote',
            old_name='observations',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='dispatchitem',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='dispatchitem',
            name='model',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='driver_id',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.client'),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='dispatch_number',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('DISPATCHED', 'Despachada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='dispatch_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dispatch_notes.dispatchnote'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='dispatch_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
