# Generated by Django 4.2 on 2025-08-22 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_cost_product_unit_price_product_category_and_more'),
        ('dispatch_notes', '0002_rename_observations_dispatchnote_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchitem',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatchitem',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='beneficiary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='driver_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='license_plate',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dispatchnote',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='dispatch_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
