# Generated by Django 4.2 on 2025-08-22 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_cost_product_unit_price_product_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch_notes', '0003_dispatchitem_brand_dispatchitem_model_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchitem',
            options={'verbose_name': 'Artículo de Despacho', 'verbose_name_plural': 'Artículos de Despacho'},
        ),
        migrations.AlterModelOptions(
            name='dispatchnote',
            options={'verbose_name': 'Nota de Despacho', 'verbose_name_plural': 'Notas de Despacho'},
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='dispatch_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dispatch_notes.dispatchnote', verbose_name='Nota de Despacho'),
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='beneficiary',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Beneficiario'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='dispatch_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Despacho'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='dispatch_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Nota'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='driver_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula del Conductor'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Conductor'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='license_plate',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Pedido'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('DISPATCHED', 'Despachada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Color del Vehículo'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Vehículo'),
        ),
    ]
