# Generated by Django 4.2 on 2025-08-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_notes', '0004_alter_dispatchitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchnote',
            options={'ordering': ['-dispatch_date'], 'verbose_name': 'Nota de Despacho', 'verbose_name_plural': 'Notas de Despacho'},
        ),
        migrations.RemoveField(
            model_name='dispatchnote',
            name='total',
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='brand',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Marca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='model',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Modelo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='beneficiary',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='Nombre del Beneficiario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='dispatch_number',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Número de Despacho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='driver_id',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='C.I. del Conductor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='driver_name',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='Nombre del Conductor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='license_plate',
            field=models.CharField(blank=True, default=1, max_length=20, verbose_name='Placa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='order_number',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='N° de Orden Asociada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('DISPATCHED', 'Despachado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='vehicle_color',
            field=models.CharField(blank=True, default=1, max_length=50, verbose_name='Color del Vehículo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='vehicle_type',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Tipo de Vehículo'),
            preserve_default=False,
        ),
    ]
