# Generated by Django 4.2 on 2025-08-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_notes', '0005_alter_dispatchnote_options_remove_dispatchnote_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchnote',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='dispatchitem',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='driver_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='C.I. del Conductor'),
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Conductor'),
        ),
    ]
