# Generated by Django 4.2 on 2025-09-24 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Nota')),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Recepción')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Nota de Recepción',
                'verbose_name_plural': 'Notas de Recepción',
            },
        ),
        migrations.CreateModel(
            name='ReceptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto')),
                ('receipt_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reception_notes.receptionnote', verbose_name='Nota de Recepción')),
            ],
            options={
                'verbose_name': 'Artículo de Recepción',
                'verbose_name_plural': 'Artículos de Recepción',
            },
        ),
    ]
