# Generated by Django 4.2 on 2025-08-21 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_cost_product_unit_price_product_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reception_notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receptionnote',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receptionnote',
            name='reception_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receptionnote',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('VALIDATED', 'Validada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='receptionnote',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
