# Generated by Django 4.2 on 2025-08-24 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_rename_cost_product_unit_price_product_category_and_more'),
        ('reception_notes', '0002_receptionitem_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receptionitem',
            options={'verbose_name': 'Artículo de Recepción', 'verbose_name_plural': 'Artículos de Recepción'},
        ),
        migrations.AlterModelOptions(
            name='receptionnote',
            options={'verbose_name': 'Nota de Recepción', 'verbose_name_plural': 'Notas de Recepción'},
        ),
        migrations.RemoveField(
            model_name='receptionitem',
            name='reception_note',
        ),
        migrations.RemoveField(
            model_name='receptionnote',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='receptionnote',
            name='reception_date',
        ),
        migrations.RemoveField(
            model_name='receptionnote',
            name='reception_number',
        ),
        migrations.AddField(
            model_name='receptionitem',
            name='receipt_note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reception_notes.receptionnote', verbose_name='Nota de Recepción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receptionnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='receptionnote',
            name='receipt_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Recepción'),
        ),
        migrations.AddField(
            model_name='receptionnote',
            name='receipt_number',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Número de Nota'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receptionnote',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='receptionitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='receptionitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='receptionitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='receptionitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='receptionnote',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='receptionnote',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='receptionnote',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Proveedor'),
        ),
    ]
