# Generated by Django 4.2 on 2025-08-21 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movements', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='delivered_to',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='movement_number',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
