# Generated by Django 4.2 on 2025-08-24 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_rename_cost_product_unit_price_product_category_and_more'),
        ('movements', '0003_remove_movement_delivered_to_remove_movement_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='delivered_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Entregado a'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario'),
        ),
    ]
