# Generated by Django 4.2 on 2025-09-24 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('dispatch_notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Devolución')),
                ('return_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Devolución')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RETURNED', 'Devuelta'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('dispatch_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch_notes.dispatchnote', verbose_name='Nota de Despacho Original')),
            ],
            options={
                'verbose_name': 'Nota de Devolución',
                'verbose_name_plural': 'Notas de Devolución',
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto')),
                ('return_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnnote', verbose_name='Nota de Devolución')),
            ],
            options={
                'verbose_name': 'Artículo de Devolución',
                'verbose_name_plural': 'Artículos de Devolución',
            },
        ),
    ]
