# Generated by Django 4.2 on 2025-08-21 18:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_cost_product_unit_price_product_category_and_more'),
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returnnote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.client'),
        ),
        migrations.AlterField(
            model_name='returnnote',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='returnnote',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSED', 'Procesada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20),
        ),
    ]
