# Generated by Django 4.2 on 2025-08-24 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch_notes', '0004_alter_dispatchitem_options_and_more'),
        ('inventory', '0002_rename_cost_product_unit_price_product_category_and_more'),
        ('returns', '0002_returnitem_subtotal_alter_returnnote_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnitem',
            options={'verbose_name': 'Artículo de Devolución', 'verbose_name_plural': 'Artículos de Devolución'},
        ),
        migrations.AlterModelOptions(
            name='returnnote',
            options={'verbose_name': 'Nota de Devolución', 'verbose_name_plural': 'Notas de Devolución'},
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='returnnote',
            name='returned_by',
        ),
        migrations.AddField(
            model_name='returnnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='return_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.returnnote', verbose_name='Nota de Devolución'),
        ),
        migrations.AlterField(
            model_name='returnnote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='returnnote',
            name='dispatch_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatch_notes.dispatchnote', verbose_name='Nota de Despacho Original'),
        ),
        migrations.AlterField(
            model_name='returnnote',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='returnnote',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Devolución'),
        ),
        migrations.AlterField(
            model_name='returnnote',
            name='return_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Devolución'),
        ),
        migrations.AlterField(
            model_name='returnnote',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('RETURNED', 'Devuelta'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
    ]
