# Generated by Django 4.2 on 2025-09-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_client_contact_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_person',
        ),
    ]
