# Generated by Django 4.2 on 2025-09-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_client_contact_person'),
    ]

    operations = [
    ]
